### ISSUE TITLE
Title: Click Counter using Javascript

### ISSUE THREAD

**Issue by LiQuiD-404** [WeBeginners-Community/CSS.Effects-Designs#1]
### Is your feature request related to a problem? Please describe.

A simple javascript project which counts the number of times a button is clicked and displays the same.

### Describe the solution you'd like.

I will be implementing this issue using HTML, CSS and Javascript.

### Describe alternatives you've considered.

NA.

### Add any other context or screenshots about the feature request here.

I will be working on this issue under Hacktoberfest.

**Comment by A158-debug** [comment]
Hey, @LiQuiD-404 Please assign me this task

I want to contribute

**Comment by LiQuiD-404** [comment]
@A158-debug Sorry bro, I am already working on it. You can open a new issue.

**Comment by A158-debug** [comment]
Its ok

**Comment by Sulagna-Dutta-Roy** [comment]
Currently I am not accepting Js Projects
