### ISSUE TITLE
Title: SnakeGame Using HTML CSS Java Script

### ISSUE THREAD

**Issue by sudarsan2k5** [WeBeginners-Community/CSS.Effects-Designs#124]
### Is your proposal related to a problem? Please describe.

I have a frontend project that I would like to submit for hacktoberfest.

### Add any other context or screenshots about the proposal request here.

![Screenshot 2022-10-10 131901](https://user-images.githubusercontent.com/108286640/194819862-b83f1313-e512-45b1-afdd-0637099146c5.png)

**Comment by sudarsan2k5** [comment]
@Sulagna-Dutta-Roy can you please assign me this issue under hacktoberfest.

**Comment by KaxitPandya** [comment]
@Sulagna-Dutta-Roy Please Assign This Task to me

**Comment by KaxitPandya** [comment]
@Sulagna-Dutta-Roy  I Have created a pull request regarding this please accept it

**Comment by KaxitPandya** [comment]
@Sulagna-Dutta-Roy  Please Accept my pull request, Let me know in case of any issues
