### ISSUE TITLE
Title: Some Cool CSS Loaders 

### ISSUE THREAD

**Issue by Atharv-110** [WeBeginners-Community/CSS.Effects-Designs#140]
### Is your feature request related to a problem? Please describe.

Yes, many developers seek some pre-loading animations for websites and apps so that server can send all the requirements and website can load all its components on time, and the user can have an excellent UI experience.

### Describe the solution you'd like.

I would like to add some CSS loaders to the project. Please assign me this issue.

### Describe alternatives you've considered.

Alternatives could be online platforms for the loaders or using some GIFs instead of coding them but that is an unethical way to do it.

### Add any other context or screenshots about the feature request here.

Types of Loaders: paint roll, fold loaders, spinning loaders. 3D Flips and Newton's Cradle will be added or more could be added if some idea strikes or some inspiration is provided via any source.

**Comment by Manishgupta200** [comment]
Assign this task to me. I already done similar task so it will not take too much time.

**Comment by Krrishn07** [comment]
Hello! @Sulagna-Dutta-Roy provide this opportunity by assigning me this issue,will.work with full potential labeled under hactoberfest.

**Comment by Sulagna-Dutta-Roy** [comment]
Project assigning is only on first serve first basis @Manishgupta200 assigned to you

**Comment by Manishgupta200** [comment]
@Sulagna-Dutta-Roy I solved this issue. Please look at and if it's ok then accept it under Hacktoberfest
