### ISSUE TITLE
Text Animation effect.

### ISSUE THREAD

**Issue by surbhi400** [WeBeginners-Community/CSS.Effects-Designs#142]
### Is your feature request related to a problem? Please describe.

I want to add a text animation effect which is made using HTML and CSS.

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

**Comment by surbhi400** [comment]
@Sulagna-Dutta-Roy can you please assign me this issue under hactoberfest.

**Comment by smolguy22** [comment]
@Sulagna-Dutta-Roy I have done this. please accept my pull request
