### ISSUE TITLE
Title: Add Space Animation

### ISSUE THREAD

**Issue by kunal00000** [WeBeginners-Community/CSS.Effects-Designs#163]
### Is your proposal related to a problem? Please describe.

I want to space animation where in a rocket is moving.

### Add any other context or screenshots about the proposal request here.

<img width="1437" alt="Screenshot 2022-10-15 at 1 26 45 AM" src="https://user-images.githubusercontent.com/92316166/195931627-f7dfb31a-76c1-4abd-beb4-7e60c24c4061.png">

**Comment by Krrishn07** [comment]
Greetings! @Sulagna-Dutta-Roy I am interested to work on this issue ,please assign me this so that I can work under hactoberfest
