### ISSUE TITLE
Title:  Jumping Animation

### ISSUE THREAD

**Issue by SattyamSamania** [WeBeginners-Community/CSS.Effects-Designs#172]
### Is your feature request related to a problem? Please describe.

I want to add Jumping Animation using Html and CSS.

### Describe the solution you'd like.

I can create Jumping Animation that will changes its colour when landed using CSS Animation.

### Describe alternatives you've considered.

I can create Animation using CSS.

### Add any other context or screenshots about the feature request here.

Here is the screenshot of the Animation: 
![Jumping](https://user-images.githubusercontent.com/67833888/195992212-b64ddeac-cb67-442f-808f-90acd0a6c983.jpg)

**Comment by SattyamSamania** [comment]
Hey @Sulagna-Dutta-Roy please assign this issue to me under Hacktoberfest.

**Comment by asmasifchippa786** [comment]
assign me please
