### ISSUE TITLE
Title: Adding Nav bar

### ISSUE THREAD

**Issue by sks8784** [WeBeginners-Community/CSS.Effects-Designs#195]
### Is your feature request related to a problem? Please describe.

I would like to add my nav bar made using HTML and CSS.

### Describe the solution you'd like.

I have made an attractive nav bar and would like it to be added in your respository, so kindly assign me.
 

### Describe alternatives you've considered.

Adding a new nav bar design under nav bar folder using HTML and CSS.

**Comment by iqrafirdose** [comment]
I also want to contribute to this issue. can you assign it?
