### ISSUE TITLE
Title: Image SlideShow using CSS

### ISSUE THREAD

**Issue by suryakaushik** [WeBeginners-Community/CSS.Effects-Designs#220]
### Is your feature request related to a problem? Please describe.

Aim is To show list of images without occuping much space

### Describe the solution you'd like.

Slideshow with left and right arrows and dot-buttons.

### Describe alternatives you've considered.

Responsive Image Grid can be an alternative

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/41267674/196533824-cb58a1d2-bba7-4077-a545-65905948f903.png)

**Comment by Ramubethi** [comment]
Can you please assign me the task?
