### ISSUE TITLE
Title: Create a floating label text input 

### ISSUE THREAD

**Issue by RathoreAbhiii** [WeBeginners-Community/CSS.Effects-Designs#23]
### Is your feature request related to a problem? Please describe.

I would like to create a text input for dark themed sites that will have a floating label.

### Describe the solution you'd like.

This feature will include three files, an index.html, index.css & index.js. Don't worry about the JavaScript file, I may or may not need it and if included, it will contain very basic code that will be easy to understand. 

### Describe alternatives you've considered.

None.

**Comment by asmasifchippa786** [comment]
assign me please

**Comment by Krrishn07** [comment]
Greetings! @Sulagna-Dutta-Roy please assign me this issue, would like to provide better floating label text input under hacktoberfest.

**Comment by Krrishn07** [comment]
@Sulagna-Dutta-Roy I have changed the folder as told, please review and merge my request
