### ISSUE TITLE
Glowing social media icons

### ISSUE THREAD

**Issue by srinjoy-26** [WeBeginners-Community/CSS.Effects-Designs#234]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

Add the icons 

### Describe alternatives you've considered.

None

**Comment by asmasifchippa786** [comment]
assign me please

**Comment by Ramubethi** [comment]
Can you please assign me the task?

**Comment by srinjoy-26** [comment]
Are you people blind or something, can't u guys see it's already assigned to me

**Comment by Ramubethi** [comment]
wtfffffff mf

**Comment by srinjoy-26** [comment]
> wtfffffff mf
See your language bro

**Comment by Sulagna-Dutta-Roy** [comment]
> wtfffffff mf

This is not acceptable. I will not tolarate someone use this language to this big event and my organization.

**Comment by Sulagna-Dutta-Roy** [comment]
> assign me please



Issue assigning will ve first serve first basis

**Comment by Ramubethi** [comment]
sorry:(
