### ISSUE TITLE
Unable to clone this repo

### ISSUE THREAD

**Issue by purna135** [WeBeginners-Community/CSS.Effects-Designs#272]
### What happened?

![image](https://user-images.githubusercontent.com/42216008/197469051-fa7dfef9-32c1-4b43-8db6-df5d32c0ee39.png)

### How can we reproduce this bug?

 git clone "you repo url"

### Desktop Information (Optional)

Windows 10

**Comment by Sulagna-Dutta-Roy** [comment]
Use github desktop

**Comment by purna135** [comment]
Thank you : )
