### ISSUE TITLE
Title: Hover button using CSS

### ISSUE THREAD

**Issue by mohakgupt** [WeBeginners-Community/CSS.Effects-Designs#30]
### Is your proposal related to a problem? Please describe.

I would like to add a beautiful button with hover effect under Hactoberfest 2022.

### Add any other context or screenshots about the proposal request here.

![image](https://user-images.githubusercontent.com/100181077/193424236-622e257c-601a-47e8-bb18-2e8316129419.png)

**Comment by asmasifchippa786** [comment]
assign me please
