### ISSUE TITLE
A Calculator Frontend

### ISSUE THREAD

**Issue by SparklinStar** [WeBeginners-Community/CSS.Effects-Designs#311]
### Is your proposal related to a problem? Please describe.

I want to make a front end of a calculator using CSS and HTML.
There will be no javascript involved, only the front end.

**Comment by Sulagna-Dutta-Roy** [comment]
This project will be add in HTML+CSS folder

**Comment by aryaman1202** [comment]
I would like to add up some JavaScript to the calculator so that it behaves like a proper calculator. Please reopen this issue and please assign it to me so that I could make this calculator more useful.

**Comment by SparklinStar** [comment]
@aryaman1202 Actually JS is not allowed in this repository. Only designs are allowed.

**Comment by aryaman1202** [comment]
@SparklinStar Okay I will keep this thing in mind.
