### ISSUE TITLE
 Login Pages 

### ISSUE THREAD

**Issue by ashadmuneer** [WeBeginners-Community/CSS.Effects-Designs#313]
I Want to contribute differents design of Login Pages by using HTML & CSS 
kindly, assign this project to me for SWOC3.0

**Comment by KaushalMaster** [comment]
I want to contribute login page design using HTML CSS and JS along with the TAILWIND CSS please assign me this issue

**Comment by ashadmuneer** [comment]
Ma'am assign this project to me
