### ISSUE TITLE
Title: E-commerce website for watches-iiwotshi (html, css, js)

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [WeBeginners-Community/CSS.Effects-Designs#315]
### Is your proposal related to a problem? Please describe.

Wanted to add a responsive e-commerce website for watches named iiwotshi made in html, css and js

**Comment by Sulagna-Dutta-Roy** [comment]
JS projects not accepting right now

**Comment by ARCHITABHATTAD** [comment]
@Sulagna-Dutta-Roy can I change the title to Pet Care website made with just Html and CSS

**Comment by Sulagna-Dutta-Roy** [comment]
Please raise new Issue

**Comment by ARCHITABHATTAD** [comment]
ok..thanks
