### ISSUE TITLE
3 Amazing CSS button animations

### ISSUE THREAD

**Issue by ShivaRapolu01** [WeBeginners-Community/CSS.Effects-Designs#32]
### Is your proposal related to a problem? Please describe.

I want to add 3 amazing CSS buttons animations under Hactoberfest 2022. They can be used on any websites and code is easy to understand . Please assign me this issue 

### Add any other context or screenshots about the proposal request here.

![Screenshot_20221002-004501_Edge](https://user-images.githubusercontent.com/79957651/193424939-83591bf2-b7c4-4147-9a61-66700a3e8907.jpg)

**Comment by lognoroy** [comment]
Hey , I want to make these buttons, And also I have also experience in this, Can you please give me this opportunity?
@ShivaRapolu01 
Your designs are final, or I can add some more features also?

**Comment by ShivaRapolu01** [comment]
It is good to see you contributing @lognoroy. You can raise maybe raise another issue for your designs

**Comment by ShivaRapolu01** [comment]
@Sulagna-Dutta-Roy please assign this issue to me so that I can start working on it asap

**Comment by ShivaRapolu01** [comment]
@Sulagna-Dutta-Roy can you please assign me this under Hactoberfest 2022

**Comment by ShivaRapolu01** [comment]
@Sulagna-Dutta-Roy I have raised PR for this issue, Please verify it

**Comment by asmasifchippa786** [comment]
assign me please
