### ISSUE TITLE
Title: To-Do-List

### ISSUE THREAD

**Issue by khushigarg1** [WeBeginners-Community/CSS.Effects-Designs#320]
### Explain what you want to add/change in documentation.

The todo list consists of an input field where users can enter a new task, and a button that allows them to add the task to the list. The list of tasks is displayed in an unordered list, with each task represented as a list item. Each list item includes a checkbox that allows users to mark the task as completed, a label that displays the task description, and a delete button that allows users to remove the task from the list.

**Comment by Sulagna-Dutta-Roy** [comment]
This project will be in HTML+CSS folder.
Format: HTML+CSS/ To Do List/ your codes
