### ISSUE TITLE
Title: A Responsive Pet Service Shop Website

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [WeBeginners-Community/CSS.Effects-Designs#323]
### Is your proposal related to a problem? Please describe.

Wanted To Add A Responsive Pet Service Shop Website Named Bow, Meow, & Squeak! Using HTML CSS

**Comment by Sulagna-Dutta-Roy** [comment]
This project will be in HTML+CSS folder.

**Comment by KaushalMaster** [comment]
can you please assign this issue to me\

**Comment by Sulagna-Dutta-Roy** [comment]
> can you please assign this issue to me\

This is already assigned. Kindly open another Issue
