### ISSUE TITLE
Title: the animation which can be used in a website of horoscope

### ISSUE THREAD

**Issue by alisha722** [WeBeginners-Community/CSS.Effects-Designs#326]
### Is your feature request related to a problem? Please describe.

website of love horoscope is paid attention to,if it has some good animations, this helps to being many more users to the website. If it's a dull website rarely anyone would give a visit 

### Describe the solution you'd like.

I have designed an animated pulsing heart for the love horoscope website using vibrant colors.

### Describe alternatives you've considered.

I have used HTML , CSS and javascript for designing it

**Comment by Sulagna-Dutta-Roy** [comment]
Please add this project in HTML+CSS folder
