### ISSUE TITLE
A Well Designed Analog Clock

### ISSUE THREAD

**Issue by SparklinStar** [WeBeginners-Community/CSS.Effects-Designs#327]
### Is your proposal related to a problem? Please describe.

I want to make a well-designed analog clock using HTML, and CSS.

**Comment by AnkitAnandMastery17** [comment]
I want to make a well-designed analog clock using HTML, CSS and JAVASCRIPT.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/109721758/212133407-d820757c-7481-4789-9d37-189b41abf752.png">

**Comment by abhishekbhonde** [comment]
assign me this issue
