### ISSUE TITLE
HTML + CSS Registration Page

### ISSUE THREAD

**Issue by ojasaklechayt** [WeBeginners-Community/CSS.Effects-Designs#335]
### Is your proposal related to a problem? Please describe.

I want to add a project I made when I was learning HTML and CSS. It is a beginner's project. Please assign me this I will add this in the repo.

**Comment by rohankumarchaudhary67** [comment]
HTML+CSS is not sufficient for this work So, I think here we use some JavaScript also to design user friendly and some animated design with the help of transition and all the other stuff.
So, I want to work on this issues and design properly without any other issues then Please assign me this issues for SWOC 3.0
