### ISSUE TITLE
Twitter Clone

### ISSUE THREAD

**Issue by Kinshuk2003** [WeBeginners-Community/CSS.Effects-Designs#338]
### Is your proposal related to a problem? Please describe.

I want to build Twitter clone. Plz assign me this project

### Add any other context or screenshots about the proposal request here.

technologies used will be HTML, CSS, REACTJS

**Comment by Sulagna-Dutta-Roy** [comment]
ReactJs projects not accepting now

**Comment by Kinshuk2003** [comment]
do we have to use only html and css ??

**Comment by Sulagna-Dutta-Roy** [comment]
Yess only html css
