### ISSUE TITLE
Title: Bean eater loader

### ISSUE THREAD

**Issue by muskan467** [WeBeginners-Community/CSS.Effects-Designs#343]
### Is your feature request related to a problem? Please describe.

Bean eater loader animation

### Describe the solution you'd like.

I will use html and css for it

### Describe alternatives you've considered.

Other loaders can also be created

### Add any other context or screenshots about the feature request here.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/65494453/211331205-013cfd8b-77de-4506-9007-d71202d09bbe.gif)

**Comment by aryaman1202** [comment]
I would like to contribute to this issue so please reopen this issue. Adding up some useful designs and animations will make the project look better. Kindly assign this to me for SWoC.
