### ISSUE TITLE
Title: Heart Shape with heartbeat animation using css

### ISSUE THREAD

**Issue by Srijita-Mandal** [WeBeginners-Community/CSS.Effects-Designs#36]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

I would like to create a heart shape with heartbeat animation using pure css.

### Describe alternatives you've considered.

NA

**Comment by Shaba1406** [comment]
I want to work on this issue @Sulagna-Dutta-Roy
