### ISSUE TITLE
Movie Card

### ISSUE THREAD

**Issue by Kumar-Ankit56** [WeBeginners-Community/CSS.Effects-Designs#367]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as If you are developer and know about movie API, so you have tried a card to display fetch movie API card. If you're looking for designing the card from scratch, then must use this overlay cool movie card.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (66)](https://user-images.githubusercontent.com/73521123/206837762-530dbf6e-afed-4521-b4ec-7aeeb45d55a6.png)

while hover on it image will scale and show the related text 
![Screenshot (67)](https://user-images.githubusercontent.com/73521123/206837775-5c9367a2-f7b9-467d-9f0c-ef0bc93dcb7a.png)

This is just sample design. Final project will be improved one.

**Comment by Kumar-Ankit56** [comment]
@Sulagna-Dutta-Roy please help me know should I create new folder for card. If not, then where I can put it.

**Comment by Sulagna-Dutta-Roy** [comment]
Heyy I will add one folder. Sorry for the late reply

**Comment by Kumar-Ankit56** [comment]
> Heyy I will add one folder. Sorry for the late reply

Please add so that I can push my code there.
