### ISSUE TITLE
Title:  A To-Do application

### ISSUE THREAD

**Issue by radzhiv25** [WeBeginners-Community/CSS.Effects-Designs#390]
### Is your proposal related to a problem? Please describe.

A To-do Application can be made to help out with day to day to-do tasks

### Add any other context or screenshots about the proposal request here.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/84130482/212747213-aa1ca2c0-99e4-4ded-a670-5a98e50c75e7.png">

**Comment by Sulagna-Dutta-Roy** [comment]
Please try not to use JS for this.

**Comment by radzhiv25** [comment]
> Please try not to use JS for this.

Just the UI then ??

**Comment by Sulagna-Dutta-Roy** [comment]
Yeah

**Comment by daredevil3435** [comment]
I want to contribute to this issue.

**Comment by Sulagna-Dutta-Roy** [comment]
Hi @radzhiv25 are you still working on this one?

**Comment by radzhiv25** [comment]
> Hi @radzhiv25 are you still working on this one?

I am not able to move ahead due to the file naming issue in the repo 
If it is resolved then i can move ahead and submit the PR

**Comment by Sulagna-Dutta-Roy** [comment]
Hi,you can check my repo Css animations folder. I've deleted the file.
And others are pushing codes through git

**Comment by radzhiv25** [comment]
> Hi,you can check my repo Css animations folder. I've deleted the file. And others are pushing codes through git

Still not able to resolve it my code is ready but that git error is not allowing me.

**Comment by Sulagna-Dutta-Roy** [comment]
You can do it on the GitHub website or desktop one. 
Others are easily done through git also. I don't know why it's happening even after deleting the junk files.
Update the fork also
