### ISSUE TITLE
Random Password Generator 

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [WeBeginners-Community/CSS.Effects-Designs#404]
This project will create a strong password for the user by combining uppercase characters, lowercase characters, numbers and symbols.
The user can the give password length.
Please assign this issue to me, I am willing to work on it!

*Screenshots*:
![197980540-b6bc049e-906e-4e91-90f1-ae4d66692b6d](https://user-images.githubusercontent.com/95978839/213117164-0a811062-2338-47a7-8054-91c0b1a8d672.png)

**Comment by Ultimateutkarsh11** [comment]
Please assign this issue to me.
@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Is this a JS project ?

**Comment by Ultimateutkarsh11** [comment]
> Is this a JS project ?

Yes, a little bit of JS is used in this project.
But I just want to add the UI part which uses HTML and CSS only.
