### ISSUE TITLE
Title: Random quote generation

### ISSUE THREAD

**Issue by Amit0412** [WeBeginners-Community/CSS.Effects-Designs#405]
### Is your feature request related to a problem? Please describe.

Tech stack : HTML , CSS and JavaScript

In this project, I will create an app that displays random famous quotes each time a button is clicked. I will make sure to  display a quote from a famous and historical figure:

Kindly assign me this issue.

### Describe the solution you'd like.

I will create an array of objects which will have some quotes and create a button so each time if button is clicked then quote will displayed on the screen.

### Describe alternatives you've considered.

NA

**Comment by aryaman1202** [comment]
Hey, I would like to work on this issue. Please assign it to me so that I could get the best out of it.

**Comment by Amit0412** [comment]
@aryaman1202 How this issue can be assigned to you? I have created this issue so first the owner of this repo will assign to me if she finds it correct and if afterassigning I upload my code and later u want to enhance my code then u can do.

**Comment by Amit0412** [comment]
Please assign me this issue @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Js projects not accepted
