### ISSUE TITLE
Title: Image Slideshow

### ISSUE THREAD

**Issue by monishkajha17** [WeBeginners-Community/CSS.Effects-Designs#431]
### Is your proposal related to a problem? Please describe.

NA

### Add any other context or screenshots about the proposal request here.

Here I will create a image slideshow where the images will shown automatically by animation.
![Screenshot (262)](https://user-images.githubusercontent.com/109274817/213976515-08e70273-fb60-4341-ad74-8ce756cbae69.png)

**Comment by Sulagna-Dutta-Roy** [comment]
this issue already exists
