### ISSUE TITLE
Title:  Landing page 

### ISSUE THREAD

**Issue by Laraibnehal** [WeBeginners-Community/CSS.Effects-Designs#432]
### Is your proposal related to a problem? Please describe.

Made this simple page with elegant css styling and beginner friendly project .

### Add any other context or screenshots about the proposal request here.

![travel](https://user-images.githubusercontent.com/95610027/214044334-57a0d595-5935-4df2-ac49-5c35e364dc35.png)

**Comment by sudarsan2k5** [comment]
Can i work on this issue?
