### ISSUE TITLE
Title: Typos in Readme.md

### ISSUE THREAD

**Issue by VaibhavArora314** [WeBeginners-Community/CSS.Effects-Designs#434]
### Explain what you want to add/change in documentation.

There are various typos in the documentation of this project.
Please assign this to me, I am willing to work on it.

Some of the typos are:

https://github.com/WeBeginners-Community/CSS.Effects-Designs/blob/d9ae8462ec0b94f534291c27569a5b4187282827/README.md?plain=1#L3

``` diff
- respository
+ repository
- Projects is accepted
+ Projects are accepted
```

---

https://github.com/WeBeginners-Community/CSS.Effects-Designs/blob/d9ae8462ec0b94f534291c27569a5b4187282827/README.md?plain=1#L10

``` diff
- animatios
+ animations
```

---

https://github.com/WeBeginners-Community/CSS.Effects-Designs/blob/d9ae8462ec0b94f534291c27569a5b4187282827/README.md?plain=1#L12

``` diff
- develope
+ develop
- the
+ then
```

**Comment by Sulagna-Dutta-Roy** [comment]
Thanks for raising but will not consider for swoc
