### ISSUE TITLE
Title: Gooey Cursor

### ISSUE THREAD

**Issue by khushigarg1** [WeBeginners-Community/CSS.Effects-Designs#441]
### Is your feature request related to a problem? Please describe.

TechStack:- HTML,CSS, JAVASCRIPT
 gooey cursor is a visual effect that makes a cursor on a webpage appear to be made of a fluid or elastic material. The cursor appears to stretch and deform as it moves around the page, giving the impression of a blob or drop of liquid.

### Describe the solution you'd like.

The HTML creates the basic cursor element, the CSS styles it and animates the movement and appearance of the cursor, and the JavaScript updates the cursor's position as the mouse moves.
It's a subtle effect, but it can add a touch of creativity and interactivity to a website. It's mostly used in creative or experimental websites, but it can be also used in games or interactive pages.

### Add any other context or screenshots about the feature request here.

![Screenshot (87)](https://user-images.githubusercontent.com/84948160/214497892-945a389b-a8ef-4472-a126-088fe1e2e6c7.png)

https://user-images.githubusercontent.com/84948160/214498094-d4d1645d-fa99-48a1-9ab9-0cde2eb6cbe9.mp4

_No response_

**Comment by khushigarg1** [comment]
Please assign this issue to me!

**Comment by Sulagna-Dutta-Roy** [comment]
Js projects not accepting
