### ISSUE TITLE
Title: Scientific Calculator

### ISSUE THREAD

**Issue by khushigarg1** [WeBeginners-Community/CSS.Effects-Designs#442]
### Is your feature request related to a problem? Please describe.

Yes Techstack:- html, css, Javascript

### Describe the solution you'd like.

I created a responsive scientific calculator using HTML, CSS, and JavaScript.The calculator includes various features such as scientific functions and a clear/reset button. I also handled various errors that could occur during calculations, such as invalid input and improper expression.

### Describe alternatives you've considered.

No

### Add any other context or screenshots about the feature request here.
![calc1](https://user-images.githubusercontent.com/84948160/214498676-136f27bd-f167-4664-b4c9-47716adf7e6e.png)

**Comment by Sulagna-Dutta-Roy** [comment]
Js projects not accepting.
This project already exists with another name in my repo
