### ISSUE TITLE
Title: Snowflakes effect using pure CSS

### ISSUE THREAD

**Issue by LiQuiD-404** [WeBeginners-Community/CSS.Effects-Designs#46]
### Is your feature request related to a problem? Please describe.

Simple snowflakes falling animation made using pure CSS.Simple

### Describe the solution you'd like.

The animation will be made using HTML and CSS.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

I will be working on this issue under Hacktoberfest'22

**Comment by asmasifchippa786** [comment]
assign me please
