### ISSUE TITLE
Title: Adding birthday template as new css project

### ISSUE THREAD

**Issue by Neha00011** [WeBeginners-Community/CSS.Effects-Designs#469]
### Is your proposal related to a problem? Please describe.

I think it would be great if we add a birthday template using html and css(mainly) in html+css folder.

**Comment by Neha00011** [comment]
@Sulagna-Dutta-Roy I am facing trouble to clone the whole repository as some files are private.It would be great if you guide me to solve thsi matter .

**Comment by Sulagna-Dutta-Roy** [comment]
I've removed those files already.Kindly re-fork it 
And check everyone is pushing codes through git

**Comment by Neha00011** [comment]
Ok, thanks a lot I will check it out.
