### ISSUE TITLE
Currency converter website using API

### ISSUE THREAD

**Issue by charu1603** [WeBeginners-Community/CSS.Effects-Designs#475]
This is a currency converter in which user can convert the currency .
Tech stack :- HTML ,  CSS , JAVASCRIPT , Currency conveter Api
![Screenshot (275)](https://user-images.githubusercontent.com/96014425/215719917-5365715a-7b87-49c1-893f-b691f2409157.png)

**Comment by charu1603** [comment]
I want to contribute on this issue under swoc Kindly assign this to me.

**Comment by Sulagna-Dutta-Roy** [comment]
Js projects not accepting
