### ISSUE TITLE
Add minimalist website in the HTML + CSS folder

### ISSUE THREAD

**Issue by Mohasin-Haque** [WeBeginners-Community/CSS.Effects-Designs#52]
### Is your feature request related to a problem? Please describe.

I didn't found any minimalist website template using HTML and CSS in this repo.

### Describe the solution you'd like.

This is a fitness website template, It uses some advanced concepts of CSS. 

### Describe alternatives you've considered.

I will create the basic home page and sidebar and it will be fully responsive so that if anyone want to work on any fitness app he can use this template.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/72180173/193467728-18dafd8e-78db-454c-815f-c84e7ab2f08c.png)
The following section videos will pay at the defined touchpoints when user scrolls.
![image](https://user-images.githubusercontent.com/72180173/193467759-9407f8e7-2501-48fe-83b3-90c95973db67.png)

**Comment by Mohasin-Haque** [comment]
Please assign this issue to me so that I can proceed. Thank You

**Comment by Mohasin-Haque** [comment]
@Sulagna-Dutta-Roy I have raised the PR. Kindly review.

**Comment by asmasifchippa786** [comment]
assign me please
