### ISSUE TITLE
Title: Food Website Lading Page

### ISSUE THREAD

**Issue by sumitkr2000** [WeBeginners-Community/CSS.Effects-Designs#543]
### Is your feature request related to a problem? Please describe.

Hey, @Sulagna-Dutta-Roy I want to add a landing page for a food website created using HTML, CSS, and javascript. Please assign me this issue. Thank you!

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![218267409-6d89f821-a787-4b6e-9a81-2e15e6001dd0](https://user-images.githubusercontent.com/100675296/218306408-38492c58-a624-4dc7-a214-b30465a6d56a.png)

**Comment by Sulagna-Dutta-Roy** [comment]
Js projects not accepting

**Comment by sumitkr2000** [comment]
Sorry its completely made using html and css. I write it by mistake assign me @Sulagna-Dutta-Roy
