### ISSUE TITLE
About new project 

### ISSUE THREAD

**Issue by NaMiKA0305** [WeBeginners-Community/CSS.Effects-Designs#550]
## ❓ Questions and Help
Hello can I add chatbot as project 

Please contact me instead.

- [Email](mailto:sulagnadutta65@gmail.com)
- [GitHub](https://github.com/sulagna-dutta-roy)
- [Instagram](https://www.instagram.com/____goodtime65/)
- [LinkedIn](https://www.linkedin.com/in/sulagna-dutta-roy/)

**Comment by Sulagna-Dutta-Roy** [comment]
Currently JS projects not accepting.
