### ISSUE TITLE
Title: Responsive Landing Page Using Bootstrap and CSS

### ISSUE THREAD

**Issue by goyalh4164** [WeBeginners-Community/CSS.Effects-Designs#564]
### Is your proposal related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/98226383/219870193-c1e5d261-6755-4eee-b7a4-4e1dfdf6bbcd.png)
![image](https://user-images.githubusercontent.com/98226383/219870215-4eb8d7bc-bf5a-4d2a-b620-cbd04e38f36e.png)
![image](https://user-images.githubusercontent.com/98226383/219870227-53810a98-0cb3-4dbf-bdaa-e80c320674dc.png)
![image](https://user-images.githubusercontent.com/98226383/219870243-b1b18c37-be6e-4d44-b2bc-32464d2c9d09.png)
![image](https://user-images.githubusercontent.com/98226383/219870249-d60fccd4-e461-42d4-881b-fffbb333e285.png)
![image](https://user-images.githubusercontent.com/98226383/219870254-e3fa42ec-082d-432f-801c-f59a4d10c43d.png)
![image](https://user-images.githubusercontent.com/98226383/219870261-74009b27-d827-4c66-ba2c-0a5d4e258ed9.png)

### Add any other context or screenshots about the proposal request here.

This webpage contains all the bootstrap components that can be reused in other websites also .
It is a refracted code i.e It does not contain any repitation

**Comment by Sulagna-Dutta-Roy** [comment]
Tech stack?

**Comment by goyalh4164** [comment]
HTML, CSS and Bootstrap only
