### ISSUE TITLE
Title: CyberPunk buttons 

### ISSUE THREAD

**Issue by Arihant1009** [WeBeginners-Community/CSS.Effects-Designs#58]
### Is your feature request related to a problem? Please describe.

Wanted to create two versions of cyberpunk button

### Describe the solution you'd like.

consider using html and css only

### Describe alternatives you've considered.

Might use sass if required

(plz assign under Hacktoberfest)

### Add any other context or screenshots about the feature request here.

![btn](https://user-images.githubusercontent.com/69034460/193502538-f0a232a4-11b8-4e05-8038-df9b34421417.svg)

**Comment by asmasifchippa786** [comment]
assign me please
