### ISSUE TITLE
Title: CSS Button

### ISSUE THREAD

**Issue by Rittika1234** [WeBeginners-Community/CSS.Effects-Designs#61]
### Is your proposal related to a problem? Please describe.

I would like to add a button using CSS and HTML . Please assign me this issue.

### Add any other context or screenshots about the proposal request here.

![Screenshot (108)](https://user-images.githubusercontent.com/98543049/193575781-35b41e1d-3755-4469-a4f3-141161251eee.png)
![Screenshot (109)](https://user-images.githubusercontent.com/98543049/193575812-fb13dd24-e3a5-49eb-bed2-067a32504da0.png)

**Comment by asmasifchippa786** [comment]
assign me please

**Comment by Sulagna-Dutta-Roy** [comment]
> assign me please

This project is already done
