### ISSUE TITLE
Title: Add Google Page Clone

### ISSUE THREAD

**Issue by SattyamSamania** [WeBeginners-Community/CSS.Effects-Designs#628]
### Is your feature request related to a problem? Please describe.

I want to add a Google Page Clone made with HTML and CSS only,

### Describe the solution you'd like.

A Google Page Clone with the look of Official Google homepage but it is static one.

### Describe alternatives you've considered.

No.

### Add any other context or screenshots about the feature request here.

![Screenshot (289)](https://user-images.githubusercontent.com/67833888/222871200-38b89cec-2d9c-45e0-9026-5ac02fabb06d.png)

**Comment by alexeevrevan** [comment]
Hey! Could you assign this to me?
