### ISSUE TITLE
Add a Custom Ice Cream Maker in the "Games" section

### ISSUE THREAD

**Issue by Adit0507** [WeBeginners-Community/CSS.Effects-Designs#63]
### Is your feature request related to a problem? Please describe.

This is a really fun project to make for developers looking to practice and brush up their skills in HTML, CSS and JavaScript.

### Describe the solution you'd like.

Live Site: https://adit0507.github.io/Custom-IceCream-Maker/

### Describe alternatives you've considered.

N/A

**Comment by Adit0507** [comment]
@Sulagna-Dutta-Roy Should I proceed ?

**Comment by Sulagna-Dutta-Roy** [comment]
Sure
