### ISSUE TITLE
Title: Add an animated hamburger button

### ISSUE THREAD

**Issue by guisantosfr** [WeBeginners-Community/CSS.Effects-Designs#64]
### Is your feature request related to a problem? Please describe.

I'd like to add an animated button that can be used in a navbar, for example.

### Describe the solution you'd like.

Like this, but simpler: https://codepen.io/roydigerhund/pen/ZQmbNm

### Describe alternatives you've considered.

Just using tranforms, not keyframes.

**Comment by Sulagna-Dutta-Roy** [comment]
Add this project but make sure the code is different with codepen. Otherwise it will be plagiarized
