### ISSUE TITLE
Title: Animated Confetti Button

### ISSUE THREAD

**Issue by its-harsshhh** [WeBeginners-Community/CSS.Effects-Designs#66]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like.

Confetti button usually made for showing succession of task. for example: Submit button

### Describe alternatives you've considered.

Here I use little bit of javascript for the dynamic animation along with CSS

**Comment by its-harsshhh** [comment]
I am contributing under hacktoberfest
kindly assign this issue to me!

**Comment by its-harsshhh** [comment]
@Sulagna-Dutta-Roy kindly tell me the folder name to reduce the further changes in this pull request

**Comment by its-harsshhh** [comment]
and also the where to save the files

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly add the project on Button folder. And name the folder as 'Confetti Button'
