### ISSUE TITLE
SpaceX Website Homepage clone

### ISSUE THREAD

**Issue by prjailani** [WeBeginners-Community/CSS.Effects-Designs#665]
### Is your feature request related to a problem? Please describe.

I like to make a SpaceX Website Homepage clone using HTML+CSS. @Sulagna-Dutta-Roy pls assign this to me. Thanks.

### Describe the solution you'd like.

I am going to use HTML and CSS

### Describe alternatives you've considered.

No

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already here
