### ISSUE TITLE
Buy me a coffee landing page

### ISSUE THREAD

**Issue by Shu12388y** [WeBeginners-Community/CSS.Effects-Designs#669]
### Is your proposal related to a problem? Please describe.

![Screenshot from 2023-07-04 21-26-36](https://github.com/WeBeginners-Community/CSS.Effects-Designs/assets/91714143/9cd3ea70-ba47-4d83-9d5f-179a5f6b4cd9)

## I want to add a landing page of buy me a Coffee

@Sulagna-Dutta-Roy  can you assign this issue to me

**Comment by Shu12388y** [comment]
@Sulagna-Dutta-Roy Hi, the issue section SWOC'23 label is mentioned in the DocBook repo. Is it an open-source program?

**Comment by Shu12388y** [comment]
@Sulagna-Dutta-Roy can you tell me about it ?

**Comment by Sulagna-Dutta-Roy** [comment]
Docbook repo selected for swoc program. Now it's over

**Comment by Shu12388y** [comment]
@Sulagna-Dutta-Roy swoc held every year?

**Comment by Sulagna-Dutta-Roy** [comment]
Yes
