### ISSUE TITLE
Title: Theme clock

### ISSUE THREAD

**Issue by sanil011** [WeBeginners-Community/CSS.Effects-Designs#71]
I would like to add a  Theme Clock.

A clock made using CSS and also show correct time with the help of some javascript line of code.

Also have a button that can make transition from dark theme to light theme or light theme to dark theme.

please assign me this

<img width="1440" alt="Screenshot 2022-10-04 at 3 42 11 AM" src="https://user-images.githubusercontent.com/105095685/193695300-71df39ca-2945-4901-b529-2a3e703f16bc.png">

**Comment by Mayank1170** [comment]
i will already work on the projects like this, can you please asign it to me.
