### ISSUE TITLE
Title: Application Development Website

### ISSUE THREAD

**Issue by Atharv-110** [WeBeginners-Community/CSS.Effects-Designs#84]
### Is your feature request related to a problem? Please describe.

In this era, everything is going online. So by seeing this a lot of people need a platform or websites to give their services on the internet. For this, I have made a Landing page + website for an Application Development & Solution providing company.

### Describe the solution you'd like.

I have a landing + a full webpage to overcome the problem above. I will be based on HTML, CSS, and JavaScript with awesome UI/UX.

### Describe alternatives you've considered.

An alternative could be made using WordPress or other web development technologies.

### Add any other context or screenshots about the feature request here.

Preview Image:
![image](https://user-images.githubusercontent.com/87393095/194167313-bf972fd5-e278-4efd-8784-852a8e176fe8.png)

### Consider and Assign this issue to me under Hacktoberfest 2022 and please add hactoberfest tags.

**Comment by Sulagna-Dutta-Roy** [comment]
JAVAscript related projects not accepting right now

**Comment by Atharv-110** [comment]
Actually this is an landing page
