### ISSUE TITLE
wave form label

### ISSUE THREAD

**Issue by sanil011** [WeBeginners-Community/CSS.Effects-Designs#89]
### Is your proposal related to a problem? Please describe.

Yes, A good animation could be set.

i would like to add a login page with good  animation when we click on search bar.

please assign me this

https://user-images.githubusercontent.com/105095685/194417133-9b2f7bf1-c4f6-4a2c-a50a-216c5016c26e.mov

**Comment by asmasifchippa786** [comment]
assign me please
